#!/bin/bash
# Jarvis Architect - Workspace Generator
# Processes templates and creates a complete agent workspace.
#
# Usage:
#   Interactive:  bash scripts/generate.sh <output-dir>
#   From config:  bash scripts/generate.sh <output-dir> <config-file>
#   Quick mode:   bash scripts/generate.sh --quick <output-dir>
#
# The config file is a simple KEY=VALUE file with template variables.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATE_DIR="$SKILL_DIR/templates"

# Load defaults library
source "$SKILL_DIR/lib/defaults.sh"

# --- Parse args ---
QUICK_MODE=false
INTERACTIVE=false

if [ "${1:-}" = "--quick" ]; then
  QUICK_MODE=true
  shift
fi

OUTPUT_DIR="${1:?Usage: generate.sh [--quick] <output-dir> [config-file]}"
CONFIG_FILE="${2:-}"

if [ -z "$CONFIG_FILE" ]; then
  INTERACTIVE=true
fi

# --- Interactive prompt helper ---
ask() {
  local var="$1" prompt="$2" default="${3:-}"
  if [ -n "$default" ]; then
    read -rp "$prompt [$default]: " value
    eval "$var=\"\${value:-$default}\""
  else
    read -rp "$prompt: " value
    eval "$var=\"\$value\""
  fi
}

# --- Interactive / Quick mode ---
if [ "$INTERACTIVE" = true ]; then
  echo "=== Jarvis Architect - Interactive Setup ==="
  echo ""

  ask AGENT_NAME "Agent name (e.g., Atlas, Nova)" ""
  ask AGENT_ROLE "Agent role (e.g., backend developer, copywriter)" ""
  AGENT_SLUG=$(echo "$AGENT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

  if [ "$QUICK_MODE" = true ]; then
    ask USER_NAME "Your name" ""
    # Apply smart defaults from lib/defaults.sh
    apply_defaults
  else
    echo ""
    echo "--- Identity ---"
    ask PERSONALITY_SUMMARY "Brief personality description" "A reliable and skilled $AGENT_ROLE focused on quality work."
    ask PRIMARY_CHANNEL "Primary channel (discord/whatsapp/telegram/slack)" "discord"
    ask MODEL "AI model" "anthropic/claude-sonnet-4-20250514"
    echo ""
    echo "--- User Profile ---"
    ask USER_NAME "Your name" ""
    ask USER_ROLE "Your role" "Manager"
    ask TIMEZONE "Your timezone" "America/New_York"
    ask AVAILABLE_HOURS "Your available hours" "9am-6pm weekdays"
    ask COMM_STYLE "Your communication style" "Brief and technical"
    ask UPDATE_FREQUENCY "How often do you want updates?" "On task completion"
    ask PREFERRED_CHANNEL "Preferred channel for updates" "$PRIMARY_CHANNEL"
    ask DETAIL_LEVEL "Detail level (concise/detailed)" "Concise with relevant details"
    ask USER_CONTEXT "Brief context about your setup" ""
    echo ""
    echo "--- Org Structure ---"
    ask ORG_DESCRIPTION "Agent's place in the org" "I am a $AGENT_ROLE reporting to $USER_NAME."
    ask MANAGER_NAME "Manager name and role" "$USER_NAME"
    ask MANAGER_ID "Manager ID" "human:$(echo "$USER_NAME" | tr '[:upper:]' '[:lower:]')"
    echo ""
    echo "--- Heartbeat ---"
    ask HEARTBEAT_FREQUENCY "Heartbeat frequency" "Every 30 minutes during active hours"
    ask ACTIVE_HOURS "Active hours" "9am-10pm"
    ask HEARTBEAT_MODE "Mode (reactive/semi-proactive/proactive)" "Semi-proactive"
    echo ""
    echo "--- Decision Framework ---"
    ask PRIORITY_1 "Top priority value" "Correctness"
    ask PRIORITY_2 "Second priority" "Reliability"
    ask PRIORITY_3 "Third priority" "Clarity"
    ask PRIORITY_4 "Fourth priority" "Speed"
    echo ""
    echo "--- Communication ---"
    ask TONE "Communication tone" "Professional, helpful"
    ask LENGTH_PREFERENCE "Preferred length" "Concise"
    ask FORMAT_PREFERENCE "Preferred format" "Structured with headers and bullet points"
    ask UNCERTAINTY_BEHAVIOR "When uncertain..." "Ask for clarification before guessing"
    ask SUCCESS_DEFINITION "What success looks like" "Consistently delivering high-quality work."
    ask ASSIGNMENT_STYLE "Best way to assign work" "Direct messages with clear requirements"
    ask RESPONSE_TIME "Expected response time" "Within one heartbeat cycle"
    ask COMPLETION_REPORTING "How completion is reported" "Summary of changes with relevant links"
    ask ESCALATION_PATH "How to escalate" "Message manager directly with context and options"
    echo ""
    echo "--- Priority Examples ---"
    ask CRITICAL_EXAMPLE "Critical priority example" "Production outage or data loss"
    ask HIGH_EXAMPLE "High priority example" "Blocked teammate or deadline"
    ask NORMAL_EXAMPLE "Normal priority example" "New feature request"
    ask LOW_EXAMPLE "Low priority example" "Documentation updates"
  fi

  # Write config file for reproducibility
  CONFIG_FILE="$OUTPUT_DIR/.jarvis-config"
  mkdir -p "$OUTPUT_DIR"
  {
    echo "# Auto-generated by Jarvis Architect on $(date +%Y-%m-%d)"
    for var in AGENT_NAME AGENT_ROLE AGENT_SLUG PERSONALITY_SUMMARY PRIMARY_CHANNEL MODEL \
               USER_NAME USER_ROLE TIMEZONE AVAILABLE_HOURS COMM_STYLE UPDATE_FREQUENCY \
               PREFERRED_CHANNEL DETAIL_LEVEL USER_CONTEXT ORG_DESCRIPTION MANAGER_NAME \
               MANAGER_ID HEARTBEAT_FREQUENCY ACTIVE_HOURS HEARTBEAT_MODE PRIORITY_1 \
               PRIORITY_2 PRIORITY_3 PRIORITY_4 TONE LENGTH_PREFERENCE FORMAT_PREFERENCE \
               UNCERTAINTY_BEHAVIOR SUCCESS_DEFINITION ASSIGNMENT_STYLE RESPONSE_TIME \
               COMPLETION_REPORTING ESCALATION_PATH CRITICAL_EXAMPLE HIGH_EXAMPLE \
               NORMAL_EXAMPLE LOW_EXAMPLE; do
      eval "echo \"$var=\${$var:-}\""
    done
  } > "$CONFIG_FILE"
  echo ""
  echo "Config saved to: $CONFIG_FILE"
else
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Config file not found: $CONFIG_FILE"
    exit 1
  fi
  # Load config
  set -a
  source "$CONFIG_FILE"
  set +a
  # Apply smart defaults for any missing values
  apply_defaults
fi

# --- Set computed defaults ---
DATE="${DATE:-$(date +%Y-%m-%d)}"
CREATED_DATE="${CREATED_DATE:-$DATE}"
AGENT_SLUG="${AGENT_SLUG:-$(echo "${AGENT_NAME:-agent}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')}"

echo ""
echo "=== Generating Workspace for: $AGENT_NAME ==="
echo "Output: $OUTPUT_DIR"
echo ""

# --- Create directory structure ---
mkdir -p "$OUTPUT_DIR"/{memory,crons,scripts,state,shared-context,subagents,products}

# --- Template processor ---
process_template() {
  local template="$1"
  local output="$2"

  if [ ! -f "$template" ]; then
    echo "  SKIP: Template not found: $(basename "$template")"
    return
  fi

  local content
  content=$(cat "$template")

  # Replace all known {{VAR}} placeholders
  for var in AGENT_NAME AGENT_ROLE AGENT_SLUG PERSONALITY_SUMMARY PRIMARY_CHANNEL MODEL \
             USER_NAME USER_ROLE TIMEZONE AVAILABLE_HOURS COMM_STYLE UPDATE_FREQUENCY \
             PREFERRED_CHANNEL DETAIL_LEVEL USER_CONTEXT ORG_DESCRIPTION MANAGER_NAME \
             MANAGER_ID HEARTBEAT_FREQUENCY ACTIVE_HOURS HEARTBEAT_MODE PRIORITY_1 \
             PRIORITY_2 PRIORITY_3 PRIORITY_4 TONE LENGTH_PREFERENCE FORMAT_PREFERENCE \
             UNCERTAINTY_BEHAVIOR SUCCESS_DEFINITION ASSIGNMENT_STYLE RESPONSE_TIME \
             COMPLETION_REPORTING ESCALATION_PATH CRITICAL_EXAMPLE HIGH_EXAMPLE \
             NORMAL_EXAMPLE LOW_EXAMPLE DATE CREATED_DATE; do
    eval "val=\"\${$var:-}\""
    content="${content//\{\{$var\}\}/$val}"
  done

  # Clean up handlebars block syntax (used for agent-driven full flow)
  content=$(echo "$content" | sed -E '/\{\{#(each|if)/d; /\{\{\/(each|if)/d; /\{\{@index\}\}/d; /\{\{else\}\}/d')
  # Remove lines that are entirely unreplaced handlebars placeholders (list items from blocks)
  content=$(echo "$content" | sed -E '/^[[:space:]]*[-*0-9.]*[[:space:]]*\{\{[a-z_]+\}\}[[:space:]]*$/d')
  # Remove lines with patterns like "- **{{var}}:** {{var}}"
  content=$(echo "$content" | sed -E '/\{\{[a-z_]+\}\}.*\{\{[a-z_]+\}\}/d')
  # Remove lines that are just "{{lowercase_var}}" (leftover block content)
  content=$(echo "$content" | sed -E '/^[[:space:]]*\{\{[a-z_]+\}\}[[:space:]]*$/d')
  # Remove empty markdown sections and clean up
  content=$(printf '%s' "$content" | python3 -c "
import sys, re
text = sys.stdin.read()
# Remove sections where a heading is followed only by whitespace then another heading or EOF
# Handles both ## and ### levels
for _ in range(3):  # multiple passes for nested cleanup
    text = re.sub(r'\n(#{2,} [^\n]+)\n\s*\n(?=#{1,} |\Z)', '\n', text)
# Remove any remaining empty sections at end of file
text = re.sub(r'\n(#{2,} [^\n]+)\s*$', '', text)
# Clean up excessive blank lines
text = re.sub(r'\n{3,}', '\n\n', text)
print(text.strip())
")
  # Replace any remaining unreplaced UPPER_CASE vars with (not set)
  content=$(echo "$content" | sed -E 's/\{\{[A-Z_]+\}\}/(not set)/g')

  echo "$content" > "$output"
  echo "  OK: $(basename "$output")"
}

echo "--- Core Files ---"
process_template "$TEMPLATE_DIR/SOUL.md" "$OUTPUT_DIR/SOUL.md"
process_template "$TEMPLATE_DIR/IDENTITY.md" "$OUTPUT_DIR/IDENTITY.md"
process_template "$TEMPLATE_DIR/USER.md" "$OUTPUT_DIR/USER.md"
process_template "$TEMPLATE_DIR/AGENTS.md" "$OUTPUT_DIR/AGENTS.md"
process_template "$TEMPLATE_DIR/MEMORY.md" "$OUTPUT_DIR/MEMORY.md"
process_template "$TEMPLATE_DIR/HEARTBEAT.md" "$OUTPUT_DIR/HEARTBEAT.md"
process_template "$TEMPLATE_DIR/BOOT.md" "$OUTPUT_DIR/BOOT.md"
process_template "$TEMPLATE_DIR/TOOLS.md" "$OUTPUT_DIR/TOOLS.md"

echo ""
echo "--- Support Files ---"
process_template "$TEMPLATE_DIR/crons-README.md" "$OUTPUT_DIR/crons/README.md"
process_template "$TEMPLATE_DIR/memory-daily.md" "$OUTPUT_DIR/memory/$DATE.md"

# Create metadata.yaml
cat > "$OUTPUT_DIR/metadata.yaml" << EOF
agent:
  name: $AGENT_NAME
  slug: $AGENT_SLUG
  role: $AGENT_ROLE
  model: ${MODEL:-anthropic/claude-sonnet-4-20250514}
  channel: ${PRIMARY_CHANNEL:-discord}
  created: $DATE
  architect_version: "2.3.0"
EOF
echo "  OK: metadata.yaml"

# Copy scripts
cp "$SKILL_DIR/scripts/health-check.sh" "$OUTPUT_DIR/scripts/health-check.sh"
chmod +x "$OUTPUT_DIR/scripts/health-check.sh"
echo "  OK: scripts/health-check.sh"

# Create observations file
cat > "$OUTPUT_DIR/state/observations.md" << 'EOF'
# Observations

## Runtime Learnings
_This file is updated as the agent operates. Each observation helps improve future sessions._

## Patterns Noticed
- (none yet)

## Improvement Ideas
- (none yet)
EOF
echo "  OK: state/observations.md"

# Create BOOTSTRAP.md
cat > "$OUTPUT_DIR/BOOTSTRAP.md" << EOF
# BOOTSTRAP.md - $AGENT_NAME

## First Run Checklist
- [ ] Review SOUL.md and adjust personality if needed
- [ ] Review USER.md and add any missing preferences
- [ ] Set up cron jobs per crons/README.md
- [ ] Run first heartbeat manually to verify setup
- [ ] Verify channel connectivity
- [ ] Test a simple task end-to-end

## Generated By
Jarvis Architect v2.3.0 on $DATE
EOF
echo "  OK: BOOTSTRAP.md"

echo ""
echo "=== Generation Complete ==="
echo ""

# Run health check
echo "Running health check..."
bash "$OUTPUT_DIR/scripts/health-check.sh" "$OUTPUT_DIR"
